### ISSUE TITLE
Update from boot2docker to docker-machine

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/dockertest#18]
The top page of [docker installation docs for mac](https://docs.docker.com/installation/mac/) state

"Note: This release of Docker deprecates the Boot2Docker command line in favor of Docker Machine. Use the Docker Toolbox to install Docker Machine as well as the other Docker tools."

So we should update dockertest to sue docker-machine.

**Comment by jscamac** [comment]
Building `dockertest` from the `18-docker-machine` worked on my iMac.
