### ISSUE TITLE
Dependendency on callr conflicts with new cran package

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/dockertest#29]
There is now a package called [callr](https://cran.r-project.org/web/packages/callr/index.html) on cran, which is also used in the new [rhub](https://github.com/r-hub/rhub) package. So installing either will clobber our callr package and make this version of dockertest unusable.

```
> library(dockertest)
Error : object ‘Sys_which’ is not exported by 'namespace:callr'
Error: package or namespace load failed for ‘dockertest’
```

We could rename callr, but I am reluctant to do so unless we can envisage it one day ending up on cran. Otherwise we might instead import the relevant functions into dockertest. 
Thoughts @richfitz ?

**Comment by richfitz** [comment]
Hi Daniel!

I should probably try and give dockertest some love at some point (unfortunately it's almost impossible to work on without good internet, and I don't need it at work yet so it's hard to schedule).

I think your proposed solution is good - move the functions into the package.  I think we've actually done that elsewhere.

The landscape surrounding dockertest has moved around a bunch recently; there are packages and conventions for dealing with the package installation more politely, things like `remotes` exist which avoids a lot of the heavy devtools dependency, and Gabor wrote a database of system dependencies that I'd like to depend on for this.

**Comment by dfalster** [comment]
Hi Rich,

Thanks for the feedback and solution. The proposed solution and implementation in #33 seems to be working fine. I'll keep testing via use and let you know if anything comes up.
